# Generated by Django 2.2.12 on 2022-10-10 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='wc.png', upload_to=''),
        ),
    ]
